#Populate categoryList Data
INSERT INTO categoryList(category)VALUES('Archery');
INSERT INTO categoryList(category)VALUES('Artistic Swimming');
INSERT INTO categoryList(category)VALUES('Athletics');
INSERT INTO categoryList(category)VALUES('Badminton');
INSERT INTO categoryList(category)VALUES('Basketball');
INSERT INTO categoryList(category)VALUES('Beach Volleyball');
INSERT INTO categoryList(category)VALUES('Boxing');
INSERT INTO categoryList(category)VALUES('Canoe Slalom');
INSERT INTO categoryList(category)VALUES('Canoe Sprint');
INSERT INTO categoryList(category)VALUES('Cycling BMX');
INSERT INTO categoryList(category)VALUES('Cycling Mountain Bike');
INSERT INTO categoryList(category)VALUES('Cycling Road');
INSERT INTO categoryList(category)VALUES('Cycling Track');
INSERT INTO categoryList(category)VALUES('Diving');
INSERT INTO categoryList(category)VALUES('Equestrian Dressage');
INSERT INTO categoryList(category)VALUES('Equestrian Eventing');
INSERT INTO categoryList(category)VALUES('Equestrian Jumping');
INSERT INTO categoryList(category)VALUES('Fencing');
INSERT INTO categoryList(category)VALUES('Football');
INSERT INTO categoryList(category)VALUES('Golf');
INSERT INTO categoryList(category)VALUES('Gymnastics Artistic');
INSERT INTO categoryList(category)VALUES('Gymnastics Rhythmic');
INSERT INTO categoryList(category)VALUES('Handball');
INSERT INTO categoryList(category)VALUES('Hockey');
INSERT INTO categoryList(category)VALUES('Judo');
INSERT INTO categoryList(category)VALUES('Marathon Swimming');
INSERT INTO categoryList(category)VALUES('Modern Pentathlon');
INSERT INTO categoryList(category)VALUES('Rowing');
INSERT INTO categoryList(category)VALUES('Rugby');
INSERT INTO categoryList(category)VALUES('Sailing');
INSERT INTO categoryList(category)VALUES('Shooting');
INSERT INTO categoryList(category)VALUES('Swimming');
INSERT INTO categoryList(category)VALUES('Table Tennis');
INSERT INTO categoryList(category)VALUES('Taekwondo');
INSERT INTO categoryList(category)VALUES('Tennis');
INSERT INTO categoryList(category)VALUES('Trampoline');
INSERT INTO categoryList(category)VALUES('Triathlon');
INSERT INTO categoryList(category)VALUES('Volleyball');
INSERT INTO categoryList(category)VALUES('Water Polo');
INSERT INTO categoryList(category)VALUES('WeightLifting');
INSERT INTO categoryList(category)VALUES('Wrestling Freestyle');
INSERT INTO categoryList(category)VALUES('Wrestling Greco Roman');
